apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::640168424446:role/devops-dev-eks-nodegroup-role
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::640168424446:role/devops-dev-BastionRole
      username: bastion-user
      groups:
        - system:masters

    - rolearn: arn:aws:iam::640168424446:role/eks-admin
      username: eks-admin
      groups:
        - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system